// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: compliance/compliance/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryListPendingApprovalsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListPendingApprovalsRequest) Reset()         { *m = QueryListPendingApprovalsRequest{} }
func (m *QueryListPendingApprovalsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListPendingApprovalsRequest) ProtoMessage()    {}
func (*QueryListPendingApprovalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{2}
}
func (m *QueryListPendingApprovalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListPendingApprovalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListPendingApprovalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListPendingApprovalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListPendingApprovalsRequest.Merge(m, src)
}
func (m *QueryListPendingApprovalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListPendingApprovalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListPendingApprovalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListPendingApprovalsRequest proto.InternalMessageInfo

func (m *QueryListPendingApprovalsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListPendingApprovalsResponse struct {
	Approvals  []*Approval         `protobuf:"bytes,1,rep,name=approvals,proto3" json:"approvals,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListPendingApprovalsResponse) Reset()         { *m = QueryListPendingApprovalsResponse{} }
func (m *QueryListPendingApprovalsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListPendingApprovalsResponse) ProtoMessage()    {}
func (*QueryListPendingApprovalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{3}
}
func (m *QueryListPendingApprovalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListPendingApprovalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListPendingApprovalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListPendingApprovalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListPendingApprovalsResponse.Merge(m, src)
}
func (m *QueryListPendingApprovalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListPendingApprovalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListPendingApprovalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListPendingApprovalsResponse proto.InternalMessageInfo

func (m *QueryListPendingApprovalsResponse) GetApprovals() []*Approval {
	if m != nil {
		return m.Approvals
	}
	return nil
}

func (m *QueryListPendingApprovalsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListApprovedApprovalsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListApprovedApprovalsRequest) Reset()         { *m = QueryListApprovedApprovalsRequest{} }
func (m *QueryListApprovedApprovalsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListApprovedApprovalsRequest) ProtoMessage()    {}
func (*QueryListApprovedApprovalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{4}
}
func (m *QueryListApprovedApprovalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListApprovedApprovalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListApprovedApprovalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListApprovedApprovalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListApprovedApprovalsRequest.Merge(m, src)
}
func (m *QueryListApprovedApprovalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListApprovedApprovalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListApprovedApprovalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListApprovedApprovalsRequest proto.InternalMessageInfo

func (m *QueryListApprovedApprovalsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListApprovedApprovalsResponse struct {
	Approvals  []*Approval         `protobuf:"bytes,1,rep,name=approvals,proto3" json:"approvals,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListApprovedApprovalsResponse) Reset()         { *m = QueryListApprovedApprovalsResponse{} }
func (m *QueryListApprovedApprovalsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListApprovedApprovalsResponse) ProtoMessage()    {}
func (*QueryListApprovedApprovalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{5}
}
func (m *QueryListApprovedApprovalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListApprovedApprovalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListApprovedApprovalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListApprovedApprovalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListApprovedApprovalsResponse.Merge(m, src)
}
func (m *QueryListApprovedApprovalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListApprovedApprovalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListApprovedApprovalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListApprovedApprovalsResponse proto.InternalMessageInfo

func (m *QueryListApprovedApprovalsResponse) GetApprovals() []*Approval {
	if m != nil {
		return m.Approvals
	}
	return nil
}

func (m *QueryListApprovedApprovalsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetApprovalByIDRequest struct {
	ApprovalId uint64 `protobuf:"varint,1,opt,name=approvalId,proto3" json:"approvalId,omitempty"`
}

func (m *QueryGetApprovalByIDRequest) Reset()         { *m = QueryGetApprovalByIDRequest{} }
func (m *QueryGetApprovalByIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetApprovalByIDRequest) ProtoMessage()    {}
func (*QueryGetApprovalByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{6}
}
func (m *QueryGetApprovalByIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetApprovalByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetApprovalByIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetApprovalByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetApprovalByIDRequest.Merge(m, src)
}
func (m *QueryGetApprovalByIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetApprovalByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetApprovalByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetApprovalByIDRequest proto.InternalMessageInfo

func (m *QueryGetApprovalByIDRequest) GetApprovalId() uint64 {
	if m != nil {
		return m.ApprovalId
	}
	return 0
}

type QueryGetApprovalByIDResponse struct {
	Approval *Approval `protobuf:"bytes,1,opt,name=approval,proto3" json:"approval,omitempty"`
}

func (m *QueryGetApprovalByIDResponse) Reset()         { *m = QueryGetApprovalByIDResponse{} }
func (m *QueryGetApprovalByIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetApprovalByIDResponse) ProtoMessage()    {}
func (*QueryGetApprovalByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{7}
}
func (m *QueryGetApprovalByIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetApprovalByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetApprovalByIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetApprovalByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetApprovalByIDResponse.Merge(m, src)
}
func (m *QueryGetApprovalByIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetApprovalByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetApprovalByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetApprovalByIDResponse proto.InternalMessageInfo

func (m *QueryGetApprovalByIDResponse) GetApproval() *Approval {
	if m != nil {
		return m.Approval
	}
	return nil
}

type QueryListDriverApprovalsRequest struct {
	DriverId   string             `protobuf:"bytes,1,opt,name=driverId,proto3" json:"driverId,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListDriverApprovalsRequest) Reset()         { *m = QueryListDriverApprovalsRequest{} }
func (m *QueryListDriverApprovalsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListDriverApprovalsRequest) ProtoMessage()    {}
func (*QueryListDriverApprovalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{8}
}
func (m *QueryListDriverApprovalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListDriverApprovalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListDriverApprovalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListDriverApprovalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListDriverApprovalsRequest.Merge(m, src)
}
func (m *QueryListDriverApprovalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListDriverApprovalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListDriverApprovalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListDriverApprovalsRequest proto.InternalMessageInfo

func (m *QueryListDriverApprovalsRequest) GetDriverId() string {
	if m != nil {
		return m.DriverId
	}
	return ""
}

func (m *QueryListDriverApprovalsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListDriverApprovalsResponse struct {
	Approvals  []*Approval         `protobuf:"bytes,1,rep,name=approvals,proto3" json:"approvals,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListDriverApprovalsResponse) Reset()         { *m = QueryListDriverApprovalsResponse{} }
func (m *QueryListDriverApprovalsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListDriverApprovalsResponse) ProtoMessage()    {}
func (*QueryListDriverApprovalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{9}
}
func (m *QueryListDriverApprovalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListDriverApprovalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListDriverApprovalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListDriverApprovalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListDriverApprovalsResponse.Merge(m, src)
}
func (m *QueryListDriverApprovalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListDriverApprovalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListDriverApprovalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListDriverApprovalsResponse proto.InternalMessageInfo

func (m *QueryListDriverApprovalsResponse) GetApprovals() []*Approval {
	if m != nil {
		return m.Approvals
	}
	return nil
}

func (m *QueryListDriverApprovalsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListRejectedApprovalsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListRejectedApprovalsRequest) Reset()         { *m = QueryListRejectedApprovalsRequest{} }
func (m *QueryListRejectedApprovalsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListRejectedApprovalsRequest) ProtoMessage()    {}
func (*QueryListRejectedApprovalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{10}
}
func (m *QueryListRejectedApprovalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListRejectedApprovalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListRejectedApprovalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListRejectedApprovalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListRejectedApprovalsRequest.Merge(m, src)
}
func (m *QueryListRejectedApprovalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListRejectedApprovalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListRejectedApprovalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListRejectedApprovalsRequest proto.InternalMessageInfo

func (m *QueryListRejectedApprovalsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListRejectedApprovalsResponse struct {
	Approvals  []*Approval         `protobuf:"bytes,1,rep,name=approvals,proto3" json:"approvals,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListRejectedApprovalsResponse) Reset()         { *m = QueryListRejectedApprovalsResponse{} }
func (m *QueryListRejectedApprovalsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListRejectedApprovalsResponse) ProtoMessage()    {}
func (*QueryListRejectedApprovalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{11}
}
func (m *QueryListRejectedApprovalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListRejectedApprovalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListRejectedApprovalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListRejectedApprovalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListRejectedApprovalsResponse.Merge(m, src)
}
func (m *QueryListRejectedApprovalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListRejectedApprovalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListRejectedApprovalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListRejectedApprovalsResponse proto.InternalMessageInfo

func (m *QueryListRejectedApprovalsResponse) GetApprovals() []*Approval {
	if m != nil {
		return m.Approvals
	}
	return nil
}

func (m *QueryListRejectedApprovalsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListAllApprovalsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListAllApprovalsRequest) Reset()         { *m = QueryListAllApprovalsRequest{} }
func (m *QueryListAllApprovalsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListAllApprovalsRequest) ProtoMessage()    {}
func (*QueryListAllApprovalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{12}
}
func (m *QueryListAllApprovalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListAllApprovalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListAllApprovalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListAllApprovalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListAllApprovalsRequest.Merge(m, src)
}
func (m *QueryListAllApprovalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListAllApprovalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListAllApprovalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListAllApprovalsRequest proto.InternalMessageInfo

func (m *QueryListAllApprovalsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListAllApprovalsResponse struct {
	Approvals  []*Approval         `protobuf:"bytes,1,rep,name=approvals,proto3" json:"approvals,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListAllApprovalsResponse) Reset()         { *m = QueryListAllApprovalsResponse{} }
func (m *QueryListAllApprovalsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListAllApprovalsResponse) ProtoMessage()    {}
func (*QueryListAllApprovalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240cf041823bc49c, []int{13}
}
func (m *QueryListAllApprovalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListAllApprovalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListAllApprovalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListAllApprovalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListAllApprovalsResponse.Merge(m, src)
}
func (m *QueryListAllApprovalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListAllApprovalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListAllApprovalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListAllApprovalsResponse proto.InternalMessageInfo

func (m *QueryListAllApprovalsResponse) GetApprovals() []*Approval {
	if m != nil {
		return m.Approvals
	}
	return nil
}

func (m *QueryListAllApprovalsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "compliance.compliance.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "compliance.compliance.QueryParamsResponse")
	proto.RegisterType((*QueryListPendingApprovalsRequest)(nil), "compliance.compliance.QueryListPendingApprovalsRequest")
	proto.RegisterType((*QueryListPendingApprovalsResponse)(nil), "compliance.compliance.QueryListPendingApprovalsResponse")
	proto.RegisterType((*QueryListApprovedApprovalsRequest)(nil), "compliance.compliance.QueryListApprovedApprovalsRequest")
	proto.RegisterType((*QueryListApprovedApprovalsResponse)(nil), "compliance.compliance.QueryListApprovedApprovalsResponse")
	proto.RegisterType((*QueryGetApprovalByIDRequest)(nil), "compliance.compliance.QueryGetApprovalByIDRequest")
	proto.RegisterType((*QueryGetApprovalByIDResponse)(nil), "compliance.compliance.QueryGetApprovalByIDResponse")
	proto.RegisterType((*QueryListDriverApprovalsRequest)(nil), "compliance.compliance.QueryListDriverApprovalsRequest")
	proto.RegisterType((*QueryListDriverApprovalsResponse)(nil), "compliance.compliance.QueryListDriverApprovalsResponse")
	proto.RegisterType((*QueryListRejectedApprovalsRequest)(nil), "compliance.compliance.QueryListRejectedApprovalsRequest")
	proto.RegisterType((*QueryListRejectedApprovalsResponse)(nil), "compliance.compliance.QueryListRejectedApprovalsResponse")
	proto.RegisterType((*QueryListAllApprovalsRequest)(nil), "compliance.compliance.QueryListAllApprovalsRequest")
	proto.RegisterType((*QueryListAllApprovalsResponse)(nil), "compliance.compliance.QueryListAllApprovalsResponse")
}

func init() { proto.RegisterFile("compliance/compliance/query.proto", fileDescriptor_240cf041823bc49c) }

var fileDescriptor_240cf041823bc49c = []byte{
	// 760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcf, 0x4f, 0xd4, 0x4c,
	0x18, 0xde, 0xe1, 0xfb, 0x3e, 0x02, 0x2f, 0x87, 0x4f, 0x07, 0x48, 0x4c, 0x65, 0xbb, 0xd0, 0xf8,
	0x03, 0x30, 0xb6, 0xb0, 0x28, 0x0b, 0x31, 0x44, 0x25, 0x44, 0x42, 0xe2, 0x01, 0x7b, 0x31, 0xd1,
	0x03, 0x19, 0x76, 0xc7, 0xa6, 0xd8, 0xed, 0x94, 0xb6, 0x10, 0x09, 0xe1, 0x62, 0xa2, 0x67, 0x13,
	0xe3, 0xdf, 0xa0, 0x51, 0x0f, 0x1c, 0xfc, 0x03, 0x3c, 0x98, 0xc8, 0x91, 0xc4, 0x8b, 0x27, 0x63,
	0xc0, 0xc4, 0x7f, 0xc3, 0xec, 0x74, 0xba, 0x2d, 0x6c, 0x7f, 0xb0, 0x24, 0x98, 0xbd, 0x6c, 0x66,
	0xa7, 0xef, 0x33, 0xcf, 0xf3, 0x3e, 0xf3, 0xf6, 0x7d, 0x0b, 0x23, 0x55, 0x56, 0x77, 0x2c, 0x93,
	0xd8, 0x55, 0xaa, 0xc5, 0x96, 0xeb, 0x1b, 0xd4, 0xdd, 0x52, 0x1d, 0x97, 0xf9, 0x0c, 0x0f, 0x46,
	0xfb, 0x6a, 0xb4, 0x94, 0xce, 0x93, 0xba, 0x69, 0x33, 0x8d, 0xff, 0x06, 0x91, 0xd2, 0x80, 0xc1,
	0x0c, 0xc6, 0x97, 0x5a, 0x63, 0x25, 0x76, 0x87, 0x0c, 0xc6, 0x0c, 0x8b, 0x6a, 0xc4, 0x31, 0x35,
	0x62, 0xdb, 0xcc, 0x27, 0xbe, 0xc9, 0x6c, 0x4f, 0x3c, 0x1d, 0xaf, 0x32, 0xaf, 0xce, 0x3c, 0x6d,
	0x95, 0x78, 0x82, 0x56, 0xdb, 0x9c, 0x5c, 0xa5, 0x3e, 0x99, 0xd4, 0x1c, 0x62, 0x98, 0x36, 0x0f,
	0x16, 0xb1, 0x4a, 0xb2, 0x58, 0x87, 0xb8, 0xa4, 0x1e, 0x9e, 0x77, 0x29, 0x39, 0x86, 0x38, 0x8e,
	0xcb, 0x36, 0x89, 0x15, 0x44, 0x29, 0x03, 0x80, 0x1f, 0x34, 0xb8, 0x96, 0x39, 0x54, 0xa7, 0xeb,
	0x1b, 0xd4, 0xf3, 0x95, 0x87, 0xd0, 0x7f, 0x64, 0xd7, 0x73, 0x98, 0xed, 0x51, 0x7c, 0x07, 0xba,
	0x03, 0x8a, 0x0b, 0x68, 0x18, 0x8d, 0xf6, 0x95, 0x8b, 0x6a, 0xa2, 0x23, 0x6a, 0x00, 0x9b, 0xef,
	0xdd, 0xfb, 0x51, 0x2a, 0xbc, 0xfb, 0xbd, 0x3b, 0x8e, 0x74, 0x81, 0x53, 0xd6, 0x60, 0x98, 0x1f,
	0x7c, 0xdf, 0xf4, 0xfc, 0x65, 0x6a, 0xd7, 0x4c, 0xdb, 0xb8, 0x2b, 0x04, 0x85, 0xe4, 0xf8, 0x1e,
	0x40, 0x94, 0xb0, 0x60, 0xba, 0xa2, 0x06, 0xee, 0xa8, 0x0d, 0x77, 0xd4, 0xe0, 0x52, 0x84, 0x3b,
	0xea, 0x32, 0x31, 0xa8, 0xc0, 0xea, 0x31, 0xa4, 0xf2, 0x01, 0xc1, 0x48, 0x06, 0x99, 0xc8, 0x69,
	0x0e, 0x7a, 0x43, 0x4b, 0x1a, 0x69, 0xfd, 0x33, 0xda, 0x57, 0x2e, 0xa5, 0xa4, 0x15, 0x82, 0xf5,
	0x08, 0x81, 0x17, 0x8f, 0x88, 0xed, 0xe2, 0x62, 0xaf, 0xe6, 0x8a, 0x0d, 0xb8, 0x8f, 0xa8, 0x7d,
	0x1a, 0x13, 0x1b, 0x10, 0xd1, 0xda, 0x99, 0x59, 0xf3, 0x11, 0x81, 0x92, 0xc5, 0xd6, 0x61, 0xde,
	0xcc, 0xc1, 0x45, 0xae, 0x76, 0x91, 0xfa, 0x21, 0xcf, 0xfc, 0xd6, 0xd2, 0x42, 0xe8, 0x8a, 0x0c,
	0x10, 0x92, 0x2e, 0xd5, 0xb8, 0x2b, 0xff, 0xea, 0xb1, 0x1d, 0xe5, 0x31, 0x0c, 0x25, 0xc3, 0x45,
	0x9a, 0xb7, 0xa0, 0x27, 0x8c, 0x16, 0x9e, 0xe6, 0x66, 0xd9, 0x04, 0x28, 0x2f, 0x10, 0x94, 0x9a,
	0x56, 0x2e, 0xb8, 0xe6, 0x26, 0x75, 0x5b, 0xae, 0x4d, 0x82, 0x9e, 0x1a, 0x7f, 0x22, 0xe4, 0xf5,
	0xea, 0xcd, 0xff, 0xc7, 0xae, 0xb4, 0xeb, 0xd4, 0x57, 0xfa, 0x1e, 0xc5, 0x5e, 0xad, 0x16, 0x1d,
	0x1d, 0x5c, 0xec, 0x3a, 0x5d, 0xa3, 0x55, 0xff, 0x6f, 0x15, 0x7b, 0x02, 0x5b, 0x87, 0x79, 0xf3,
	0x44, 0x54, 0x2b, 0x7f, 0x35, 0x2d, 0xeb, 0xcc, 0x6c, 0x79, 0x8b, 0xa0, 0x98, 0x42, 0xd4, 0x59,
	0x8e, 0x94, 0xdf, 0x00, 0xfc, 0xc7, 0x95, 0xe2, 0x97, 0x08, 0xba, 0x83, 0xe1, 0x82, 0xc7, 0x52,
	0x94, 0xb4, 0x4e, 0x33, 0x69, 0xfc, 0x24, 0xa1, 0x01, 0xaf, 0x72, 0xf9, 0xf9, 0xb7, 0x5f, 0xaf,
	0xbb, 0x4a, 0xb8, 0xa8, 0x65, 0x8d, 0x58, 0xfc, 0x19, 0xc1, 0x40, 0xd2, 0x58, 0xc1, 0x95, 0x2c,
	0xae, 0x8c, 0xa9, 0x27, 0xcd, 0xb4, 0x0f, 0x14, 0x92, 0x6f, 0x72, 0xc9, 0x1a, 0xbe, 0x9e, 0x22,
	0xd9, 0x32, 0x3d, 0x7f, 0xc5, 0x09, 0xd0, 0x2b, 0xd1, 0xf5, 0x7c, 0x41, 0x30, 0x98, 0xd8, 0xfe,
	0x71, 0xae, 0x94, 0xb4, 0xf9, 0x24, 0xcd, 0x9e, 0x02, 0x29, 0xb2, 0x98, 0xe6, 0x59, 0x4c, 0x60,
	0x35, 0x2b, 0x0b, 0x22, 0xe0, 0xb1, 0x34, 0x3e, 0x21, 0xf8, 0xff, 0x58, 0x63, 0xc7, 0xe5, 0x2c,
	0x19, 0xc9, 0x43, 0x44, 0x9a, 0x6a, 0x0b, 0x23, 0x44, 0xcf, 0x70, 0xd1, 0x65, 0x3c, 0x91, 0x22,
	0xda, 0xa0, 0x7e, 0x53, 0xaa, 0xb6, 0x1d, 0x8d, 0xa4, 0x1d, 0xfc, 0x15, 0x41, 0x7f, 0x42, 0xa7,
	0xc6, 0xd3, 0x79, 0x0e, 0x26, 0x8f, 0x18, 0xa9, 0xd2, 0x36, 0x4e, 0xa4, 0x70, 0x9b, 0xa7, 0x30,
	0x8b, 0x2b, 0x59, 0xbe, 0x07, 0xd3, 0x2a, 0x72, 0x5d, 0xdb, 0x0e, 0xe7, 0xd7, 0x4e, 0xb3, 0x8e,
	0x5a, 0x3a, 0x6b, 0x7e, 0x1d, 0xa5, 0xb5, 0xfe, 0xfc, 0x3a, 0x4a, 0x6d, 0xe3, 0x27, 0xab, 0x23,
	0x57, 0xc0, 0x63, 0x75, 0xb4, 0x8b, 0xe0, 0xdc, 0xf1, 0x4e, 0x88, 0xa7, 0x72, 0xeb, 0xb9, 0xb5,
	0x41, 0x4b, 0x37, 0xda, 0x03, 0x09, 0xdd, 0x93, 0x5c, 0xf7, 0x35, 0x3c, 0x96, 0x59, 0xff, 0x96,
	0x15, 0x49, 0x9e, 0xaf, 0xec, 0x1d, 0xc8, 0x68, 0xff, 0x40, 0x46, 0x3f, 0x0f, 0x64, 0xf4, 0xea,
	0x50, 0x2e, 0xec, 0x1f, 0xca, 0x85, 0xef, 0x87, 0x72, 0xe1, 0x51, 0x31, 0x06, 0x7c, 0x16, 0x3f,
	0xc5, 0xdf, 0x72, 0xa8, 0xb7, 0xda, 0xcd, 0xbf, 0xfd, 0xa7, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x56, 0x1c, 0x58, 0x8e, 0xf4, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ListPendingApprovals items.
	ListPendingApprovals(ctx context.Context, in *QueryListPendingApprovalsRequest, opts ...grpc.CallOption) (*QueryListPendingApprovalsResponse, error)
	// Queries a list of ListApprovedApprovals items.
	ListApprovedApprovals(ctx context.Context, in *QueryListApprovedApprovalsRequest, opts ...grpc.CallOption) (*QueryListApprovedApprovalsResponse, error)
	// Queries a list of GetApproval items.
	GetApprovalByID(ctx context.Context, in *QueryGetApprovalByIDRequest, opts ...grpc.CallOption) (*QueryGetApprovalByIDResponse, error)
	// Queries a list of ListDriverApprovals items.
	ListDriverApprovals(ctx context.Context, in *QueryListDriverApprovalsRequest, opts ...grpc.CallOption) (*QueryListDriverApprovalsResponse, error)
	// Queries a list of ListRejectedApprovals items.
	ListRejectedApprovals(ctx context.Context, in *QueryListRejectedApprovalsRequest, opts ...grpc.CallOption) (*QueryListRejectedApprovalsResponse, error)
	// Queries a list of ListAllApprovals items.
	ListAllApprovals(ctx context.Context, in *QueryListAllApprovalsRequest, opts ...grpc.CallOption) (*QueryListAllApprovalsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/compliance.compliance.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListPendingApprovals(ctx context.Context, in *QueryListPendingApprovalsRequest, opts ...grpc.CallOption) (*QueryListPendingApprovalsResponse, error) {
	out := new(QueryListPendingApprovalsResponse)
	err := c.cc.Invoke(ctx, "/compliance.compliance.Query/ListPendingApprovals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListApprovedApprovals(ctx context.Context, in *QueryListApprovedApprovalsRequest, opts ...grpc.CallOption) (*QueryListApprovedApprovalsResponse, error) {
	out := new(QueryListApprovedApprovalsResponse)
	err := c.cc.Invoke(ctx, "/compliance.compliance.Query/ListApprovedApprovals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetApprovalByID(ctx context.Context, in *QueryGetApprovalByIDRequest, opts ...grpc.CallOption) (*QueryGetApprovalByIDResponse, error) {
	out := new(QueryGetApprovalByIDResponse)
	err := c.cc.Invoke(ctx, "/compliance.compliance.Query/GetApprovalByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDriverApprovals(ctx context.Context, in *QueryListDriverApprovalsRequest, opts ...grpc.CallOption) (*QueryListDriverApprovalsResponse, error) {
	out := new(QueryListDriverApprovalsResponse)
	err := c.cc.Invoke(ctx, "/compliance.compliance.Query/ListDriverApprovals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListRejectedApprovals(ctx context.Context, in *QueryListRejectedApprovalsRequest, opts ...grpc.CallOption) (*QueryListRejectedApprovalsResponse, error) {
	out := new(QueryListRejectedApprovalsResponse)
	err := c.cc.Invoke(ctx, "/compliance.compliance.Query/ListRejectedApprovals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListAllApprovals(ctx context.Context, in *QueryListAllApprovalsRequest, opts ...grpc.CallOption) (*QueryListAllApprovalsResponse, error) {
	out := new(QueryListAllApprovalsResponse)
	err := c.cc.Invoke(ctx, "/compliance.compliance.Query/ListAllApprovals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ListPendingApprovals items.
	ListPendingApprovals(context.Context, *QueryListPendingApprovalsRequest) (*QueryListPendingApprovalsResponse, error)
	// Queries a list of ListApprovedApprovals items.
	ListApprovedApprovals(context.Context, *QueryListApprovedApprovalsRequest) (*QueryListApprovedApprovalsResponse, error)
	// Queries a list of GetApproval items.
	GetApprovalByID(context.Context, *QueryGetApprovalByIDRequest) (*QueryGetApprovalByIDResponse, error)
	// Queries a list of ListDriverApprovals items.
	ListDriverApprovals(context.Context, *QueryListDriverApprovalsRequest) (*QueryListDriverApprovalsResponse, error)
	// Queries a list of ListRejectedApprovals items.
	ListRejectedApprovals(context.Context, *QueryListRejectedApprovalsRequest) (*QueryListRejectedApprovalsResponse, error)
	// Queries a list of ListAllApprovals items.
	ListAllApprovals(context.Context, *QueryListAllApprovalsRequest) (*QueryListAllApprovalsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ListPendingApprovals(ctx context.Context, req *QueryListPendingApprovalsRequest) (*QueryListPendingApprovalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPendingApprovals not implemented")
}
func (*UnimplementedQueryServer) ListApprovedApprovals(ctx context.Context, req *QueryListApprovedApprovalsRequest) (*QueryListApprovedApprovalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApprovedApprovals not implemented")
}
func (*UnimplementedQueryServer) GetApprovalByID(ctx context.Context, req *QueryGetApprovalByIDRequest) (*QueryGetApprovalByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApprovalByID not implemented")
}
func (*UnimplementedQueryServer) ListDriverApprovals(ctx context.Context, req *QueryListDriverApprovalsRequest) (*QueryListDriverApprovalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDriverApprovals not implemented")
}
func (*UnimplementedQueryServer) ListRejectedApprovals(ctx context.Context, req *QueryListRejectedApprovalsRequest) (*QueryListRejectedApprovalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRejectedApprovals not implemented")
}
func (*UnimplementedQueryServer) ListAllApprovals(ctx context.Context, req *QueryListAllApprovalsRequest) (*QueryListAllApprovalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllApprovals not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compliance.compliance.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListPendingApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListPendingApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListPendingApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compliance.compliance.Query/ListPendingApprovals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListPendingApprovals(ctx, req.(*QueryListPendingApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListApprovedApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListApprovedApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListApprovedApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compliance.compliance.Query/ListApprovedApprovals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListApprovedApprovals(ctx, req.(*QueryListApprovedApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetApprovalByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetApprovalByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetApprovalByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compliance.compliance.Query/GetApprovalByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetApprovalByID(ctx, req.(*QueryGetApprovalByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDriverApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListDriverApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDriverApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compliance.compliance.Query/ListDriverApprovals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDriverApprovals(ctx, req.(*QueryListDriverApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListRejectedApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListRejectedApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListRejectedApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compliance.compliance.Query/ListRejectedApprovals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListRejectedApprovals(ctx, req.(*QueryListRejectedApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListAllApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListAllApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListAllApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compliance.compliance.Query/ListAllApprovals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListAllApprovals(ctx, req.(*QueryListAllApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compliance.compliance.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ListPendingApprovals",
			Handler:    _Query_ListPendingApprovals_Handler,
		},
		{
			MethodName: "ListApprovedApprovals",
			Handler:    _Query_ListApprovedApprovals_Handler,
		},
		{
			MethodName: "GetApprovalByID",
			Handler:    _Query_GetApprovalByID_Handler,
		},
		{
			MethodName: "ListDriverApprovals",
			Handler:    _Query_ListDriverApprovals_Handler,
		},
		{
			MethodName: "ListRejectedApprovals",
			Handler:    _Query_ListRejectedApprovals_Handler,
		},
		{
			MethodName: "ListAllApprovals",
			Handler:    _Query_ListAllApprovals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compliance/compliance/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListPendingApprovalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListPendingApprovalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListPendingApprovalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListPendingApprovalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListPendingApprovalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListPendingApprovalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Approvals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListApprovedApprovalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListApprovedApprovalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListApprovedApprovalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListApprovedApprovalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListApprovedApprovalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListApprovedApprovalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Approvals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetApprovalByIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetApprovalByIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetApprovalByIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ApprovalId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ApprovalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetApprovalByIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetApprovalByIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetApprovalByIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Approval != nil {
		{
			size, err := m.Approval.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListDriverApprovalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListDriverApprovalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListDriverApprovalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DriverId) > 0 {
		i -= len(m.DriverId)
		copy(dAtA[i:], m.DriverId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DriverId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListDriverApprovalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListDriverApprovalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListDriverApprovalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Approvals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListRejectedApprovalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListRejectedApprovalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListRejectedApprovalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListRejectedApprovalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListRejectedApprovalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListRejectedApprovalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Approvals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListAllApprovalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListAllApprovalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListAllApprovalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListAllApprovalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListAllApprovalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListAllApprovalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Approvals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListPendingApprovalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListPendingApprovalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for _, e := range m.Approvals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListApprovedApprovalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListApprovedApprovalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for _, e := range m.Approvals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetApprovalByIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ApprovalId != 0 {
		n += 1 + sovQuery(uint64(m.ApprovalId))
	}
	return n
}

func (m *QueryGetApprovalByIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Approval != nil {
		l = m.Approval.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListDriverApprovalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DriverId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListDriverApprovalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for _, e := range m.Approvals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListRejectedApprovalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListRejectedApprovalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for _, e := range m.Approvals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListAllApprovalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListAllApprovalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Approvals) > 0 {
		for _, e := range m.Approvals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListPendingApprovalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListPendingApprovalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListPendingApprovalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListPendingApprovalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListPendingApprovalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListPendingApprovalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, &Approval{})
			if err := m.Approvals[len(m.Approvals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListApprovedApprovalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListApprovedApprovalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListApprovedApprovalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListApprovedApprovalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListApprovedApprovalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListApprovedApprovalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, &Approval{})
			if err := m.Approvals[len(m.Approvals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetApprovalByIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetApprovalByIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetApprovalByIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovalId", wireType)
			}
			m.ApprovalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApprovalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetApprovalByIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetApprovalByIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetApprovalByIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Approval == nil {
				m.Approval = &Approval{}
			}
			if err := m.Approval.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListDriverApprovalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListDriverApprovalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListDriverApprovalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DriverId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DriverId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListDriverApprovalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListDriverApprovalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListDriverApprovalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, &Approval{})
			if err := m.Approvals[len(m.Approvals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListRejectedApprovalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListRejectedApprovalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListRejectedApprovalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListRejectedApprovalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListRejectedApprovalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListRejectedApprovalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, &Approval{})
			if err := m.Approvals[len(m.Approvals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListAllApprovalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListAllApprovalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListAllApprovalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListAllApprovalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListAllApprovalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListAllApprovalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, &Approval{})
			if err := m.Approvals[len(m.Approvals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
